### ISSUE TITLE
Parsing with bilstm model produces no output

### ISSUE THREAD

**Issue by around1991** [danielhers/tupa#8]
Hi guys

Sorry to be a pain, but I've got another issue to report. I can now parse my example.txt, and everything works out fine for the mlp and sparse models, but when I try to parse with the biLSTM model, the resulting example_0.xml just contains a single scene unit, and no further annotations.

Thanks!
Kris

**Comment by danielhers** [comment]
No problem at all. Thanks for reporting this. Looks like there was a problem with the BiLSTM model, but I uploaded [a new version](http://www.cs.huji.ac.il/~danielh/ucca/bilstm-1.2.tar.gz). Please download again and let me know if it worked.

**Comment by around1991** [comment]
That works, thanks for getting back to me so quickly!

**Comment by around1991** [comment]
I'm just inspecting the output of the biLSTM model (with the weights provided) - it seems to produce very odd analyses.

For instance, given the sentence 'My dog who I loved died yesterday', the MLP model produces something fairly reasonable, but the biLSTM model you provided seems to give a very strange tree, with two A's (my dog loved died yesterday) and (I) off the root. 

Is this intended behaviour?

**Comment by danielhers** [comment]
It's certainly not correct UCCA analysis, but this time it's probably because the parser simply was not trained on sentences like this, or it did not have enough training data. It was trained on just 4268 sentences from Wikipedia.
The parser demo gives [something that's almost correct](http://www.cs.huji.ac.il/~danielh/ucca/?input=The%20dog%20who%20I%20loved%20died%20yesterday&format=xml), and it is based on an older BiLSTM model whose accuracy should nevertheless be the same (around 72% F1 on the Wiki dev set). It's interesting that you're getting better analyses with the MLP model, but I suspect it's just by chance.

**Comment by danielhers** [comment]
Sorry, I take it back. I checked again and the current model gets just 60.4% F1 (primary) and 25.3% (remote) on the dev set. I found the problem, though, and I'll fix it. Thanks for bringing this to my attention.

**Comment by danielhers** [comment]
Fixed BiLSTM model.
